# This is a basic workflow to help you get started with Actions

name: CxAST Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@af050977dcd7da8d09798a3394bf17cc47660034
        uses: Checkmarx/ast-github-action@v0.29
        with:
          # Provide the AST portal URL
          base_uri: https://eu.ast.checkmarx.net/
          # Provide the Tenant for AST portal URL
          cx_tenant: cec_emea_test_emanuel_ribeiro
          # Client ID for AST portal authentication
          cx_client_id: ${{ secrets.CLIENT_ID }}
          # Secret key for AST portal authentication
          cx_client_secret: ${{ secrets.SECRET }}
          # Select a Checkmarx Project Name
          project_name: ${{ github.repository }}
          # Branch name
          branch: ${{ github.ref }}
          # GitHub API Token
          github_token: ${{ github.token }}
          # Additional parameters for AST scan
          additional_params: --report-format sarif --output-name results --debug
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
            # Path to SARIF file relative to the root of the repository
            sarif_file: results.sarif
